# Generated by Django 2.0.5 on 2018-06-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200, verbose_name='小组名')),
                ('grouplink', models.CharField(max_length=200, verbose_name='小组链接')),
                ('enable', models.BooleanField(default=False, verbose_name='是否生效')),
                ('max_page', models.IntegerField(default=1, verbose_name='获取最大页数')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicid', models.IntegerField(verbose_name='主题ID')),
                ('image_url', models.CharField(max_length=200, unique=True, verbose_name='图片地址')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicid', models.IntegerField(unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('title_url', models.CharField(default='', max_length=200, verbose_name='标题链接')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('author_name', models.CharField(max_length=50, verbose_name='作者')),
                ('author_url', models.CharField(max_length=200, verbose_name='主页')),
                ('groupid', models.IntegerField(default=0, verbose_name='分组id')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
    ]
